### ISSUE TITLE
Write spark dataframe to opensearch

### ISSUE THREAD

**Issue by shuangli-z** [shuangli-z/chatbot-test#20]
Is your feature request related to a problem? Please describe.

I am evaluating that converting es to opensearch, and my team use spark to process data.
I want to know if I can directly write spark dataframe to opensearch, just like we did on elasticsearch?
I just started following this project but didn't see a similar case on google or stack overflow, thanks for all your help!

Describe the solution you'd like
write spark dataframe to opensearch and use spark resource.

Describe alternatives you've considered

Additional context

**Comment by shuangli-z** [comment]
Yes, you can write Spark DataFrames directly to OpenSearch. OpenSearch provides integration with Apache Spark through its SQL plugin and connector settings.

To write a Spark DataFrame to OpenSearch, you'll need to:

1. Configure the OpenSearch sink with appropriate settings:
```yaml
pipeline:
  sink:
    opensearch:
      hosts: ["https://your-opensearch-endpoint"]
      bulk_size: 1000
```

2. Configure the Spark connector settings in OpenSearch with necessary parameters:
```json
{
  "spark.datasource.flint.host": "localhost",
  "spark.datasource.flint.port": "9200",
  "spark.datasource.flint.scheme": "https",
  "spark.datasource.flint.write.batch_size": "1000",
  "spark.datasource.flint.write.refresh_policy": "false"
}
```

3. For AWS OpenSearch Service, enable AWS SigV4 authentication:
```yaml
pipeline:
  sink:
    opensearch:
      hosts: ["https://your-amazon-opensearch-service-endpoint"]
      aws_sigv4: true
```

The Spark connector supports features like:
- Configurable batch sizes for writing
- Refresh policies for data consistency
- ID column handling
- Authentication methods including AWS SigV4
- Optimization settings for better performance

This functionality maintains compatibility with existing Spark DataFrame operations while providing the benefits of OpenSearch's distributed search and analytics capabilities.&nbsp;

If you want to get more detailed information, please check the OpenSearch documentation at https://opensearch.org/docs/latest/data-prepper/pipelines/configuration/sinks/opensearch/; https://opensearch.org/docs/latest/search-plugins/sql/settings/
